export default [
  {
    id: 1,
    category: 'breakfast',
    name: 'Yogurt Bowl with Oats & Apricot',
    description: 'A cup of Yogurt with half a cup of oats & a whole Apricot',
    image: 'img/meals/yogurt_apricot.jpg',
    price: '6.99',
  },
  {
    id: 2,
    category: 'breakfast',
    name: 'Pancakes with Strawberry slices & Strawberry jam',
    description: 'Three pancakes with half a 1/4 cup of Strawberry slices & 1 table spoon of of Strawberry jam.',
    image: 'img/meals/pancakes_strawberries.jpg',
    price: '5.99',
  },
  {
    id: 3,
    category: 'breakfast',
    name: 'Pancakes with Strawberry slices & Strawberry jam',
    description: 'Three pancakes with half a 1/4 cup of Strawberry slices & 1 table spoon of of Strawberry jam.',
    image: 'img/meals/pancakes_strawberries.jpg',
    price: '5.99',
  },
  {
    id: 7,
    category: 'lunch',
    name: 'Lunch name here',
    description: 'lunch description here',
    image: 'img/meals/yogurt_apricot.jpg',
    price: '15.99',
  },
  {
    id: 13,
    category: 'dinner',
    name: 'Dinner name here',
    description: 'Dinner description here',
    image: 'img/meals/pancakes_strawberries.jpg',
    price: '2.99',
  },
  {
    id: 20,
    category: 'drinks',
    name: 'Drinks name here',
    description: 'Drinks description here',
    image: 'img/meals/pancakes_strawberries.jpg',
    price: '21.99',
  },
]