export default [
  {
    id: 1,
    category: 'breakfast',
    name: 'Yogurt Bowl with Oats & Apricot',
    description: 'A cup of Yogurt with half a cup of oats & a whole Apricot',
    image: 'img/meals/yogurt_apricot.jpg',
    price: '6.99',
  },
  {
    id: 2,
    category: 'breakfast',
    name: 'Pancakes with Strawberry slices & Strawberry jam',
    description: 'Three pancakes with half a 1/4 cup of Strawberry slices & 1 table spoon of of Strawberry jam.',
    image: 'img/meals/pancakes_strawberries.jpg',
    price: '5.99',
  },
  {
    id: 3,
    category: 'breakfast',
    name: 'Croissant with Coffee',
    description: 'A medium croissant with a cup of black coffee (coffee creamers available).',
    image: 'img/meals/croissant-coffee.jpg',
    price: '4.99',
  },
  {
    id: 4,
    category: 'breakfast',
    name: 'Bowl of Oatmeal with Blueberries',
    description: 'A cup of cooked oats with a 1/4 cup of blueberries.',
    image: 'img/meals/blueberry-oats.jpg',
    price: '5.99',
  },
  {
    id: 5,
    category: 'breakfast',
    name: 'Sunnyside up Eggs with Bread Slices',
    description: 'Two sunnyside eggs with bread slices, tomatoes, and ham',
    image: 'img/meals/sunnyside-eggs.jpg',
    price: '4.99',
  },
  {
    id: 6,
    category: 'breakfast',
    name: 'Waffle Stack',
    description: 'Three waffles with 1/4 cup of blueberries and strawberries.',
    image: 'img/meals/waffles.jpg',
    price: '6.99',
  },
  {
    id: 7,
    category: 'lunch',
    name: 'Vegetable Salad',
    description: 'Enjoy a salad made up of carrots, broccoli, cucumber, brussels sprouts, and quinoa',
    image: 'img/meals/quinoa_salad.jpg',
    price: '9.99',
  },
  {
    id: 8,
    category: 'lunch',
    name: 'Avocado Toast',
    description: 'Three slices of toast with a spread of Avocado',
    image: 'img/meals/avocado_toast.jpg',
    price: '4.99',
  },
  {
    id: 9,
    category: 'lunch',
    name: 'Pasta',
    description: 'A plate of pasta with tomato and basil.',
    image: 'img/meals/pasta_basil.jpg',
    price: '6.99',
  },
  {
    id: 10,
    category: 'lunch',
    name: 'Deep Fried Shrimp & Squid',
    description: 'Deep fried Shrimp and Squid (Squid optional) with a slice of lemon.',
    image: 'img/meals/shrimp_squid.jpg',
    price: '7.99',
  },
  {
    id: 11,
    category: 'lunch',
    name: 'Fried Meat With Orange Sauce',
    description: 'Pieces of Fried Meat with orange honey sauce',
    image: 'img/meals/orange_sauce.jpg',
    price: '10.99',
  },
  {
    id: 12,
    category: 'lunch',
    name: 'Ham & Egg Bagel Sandwich',
    description: 'Cooked Ham & Omelet Egg Bagel Sandwich',
    image: 'img/meals/egg_bagel.jpg',
    price: '7.99',
  },
  {
    id: 13,
    category: 'dinner',
    name: 'Smoked Meat & Rice',
    description: 'Three large pieces of smoked meat along side a cup of fried rice.',
    image: 'img/meals/meat_rice.jpg',
    price: '8.99',
  },
  {
    id: 14,
    category: 'dinner',
    name: 'Hamburger & Fries',
    description: 'A medium (Large available) Hamburger and frieds.',
    image: 'img/meals/hamburger_fries.jpg',
    price: '5.99',
  },
  {
    id: 15,
    category: 'dinner',
    name: 'Pizza (Pick your toppings)',
    description: 'Get a Pizza for one, or for a group. Pick as many toppings as you want.',
    image: 'img/meals/pizza.jpg',
    price: '12.99',
  },
  {
    id: 16,
    category: 'dinner',
    name: 'Noodle Soup',
    description: 'Noodle soup with beef and vegetables.',
    image: 'img/meals/meat_soup.jpg',
    price: '4.99',
  },
  {
    id: 17,
    category: 'drinks',
    name: 'Beer Mug (Beer of your choosing)',
    description: 'Beer Mug (Beer of your choosing)',
    image: 'img/meals/beer.jpg',
    price: '8.99',
  },
  {
    id: 18,
    category: 'drinks',
    name: 'Red Wine (bottle included)',
    description: 'Get a 1L bottle of red wine',
    image: 'img/meals/red_wine.jpg',
    price: '29.99',
  },
  {
    id: 19,
    category: 'drinks',
    name: 'Red Wine (bottle included)',
    description: 'Get a 1L bottle of red wine',
    image: 'img/meals/red_wine.jpg',
    price: '29.99',
  },
  {
    id: 20,
    category: 'drinks',
    name: 'White Wine (bottle included)',
    description: 'Get a 1L bottle of white wine',
    image: 'img/meals/white_wine.jpg',
    price: '29.99',
  },
]