export default [
  {
    id: 1,
    category: 'breakfast',
    name: 'Yogurt Bowl with Oats & Apricot',
    description: 'A cup of Yogurt with half a cup of oats & a whole Apricot',
    image: 'img/meals/yogurt_apricot.jpg',
    price: '6.99',
  },
  {
    id: 2,
    category: 'breakfast',
    name: 'Pancakes with Strawberry slices & Strawberry jam',
    description: 'Three pancakes with half a 1/4 cup of Strawberry slices & 1 table spoon of of Strawberry jam.',
    image: 'img/meals/pancakes_strawberries.jpg',
    price: '5.99',
  },
  {
    id: 3,
    category: 'breakfast',
    name: 'Croissant with Coffee',
    description: 'A medium croissant with a cup of black coffee (coffee creamers available).',
    image: 'img/meals/croissant-coffee.jpg',
    price: '4.99',
  },
  {
    id: 4,
    category: 'breakfast',
    name: 'Bowl of Oatmeal with Blueberries',
    description: 'A cup of cooked oats with a 1/4 cup of blueberries.',
    image: 'img/meals/blueberry-oats.jpg',
    price: '5.99',
  },
  {
    id: 5,
    category: 'breakfast',
    name: 'Sunnyside up Eggs with Bread Slices',
    description: 'Two sunnyside eggs with bread slices, tomatoes, and ham',
    image: 'img/meals/sunnyside-eggs.jpg',
    price: '4.99',
  },
  {
    id: 6,
    category: 'breakfast',
    name: 'Waffle Stack',
    description: 'Three waffles with 1/4 cup of blueberries and strawberries.',
    image: 'img/meals/waffles.jpg',
    price: '6.99',
  },
  {
    id: 7,
    category: 'lunch',
    name: 'Lunch name here',
    description: 'lunch description here',
    image: 'img/meals/yogurt_apricot.jpg',
    price: '15.99',
  },
  {
    id: 13,
    category: 'dinner',
    name: 'Dinner name here',
    description: 'Dinner description here',
    image: 'img/meals/pancakes_strawberries.jpg',
    price: '2.99',
  },
  {
    id: 20,
    category: 'drinks',
    name: 'Drinks name here',
    description: 'Drinks description here',
    image: 'img/meals/pancakes_strawberries.jpg',
    price: '21.99',
  },
]